### PR TITLE
fixed compilation with OCaml 4.05

### LINKED ISSUE #3: fixe compilation with OCaml 4.05
cf. https://github.com/UnixJunkie/ptmap/pull/1

### PR DESCRIPTION
**Pull request by andyli**
caused by new functions added to the standard library's Map module

fix backtracking/ptmap#3

### CODE REVIEW

**Comment by andyli** [comment]
Would you look into it soon? The library is not installable using opam with ocaml 4.05 without this fix.

**Comment by thomasuster** [comment]
Yes please!

**Comment by ilovezfs** [comment]
@UnixJunkie gentle ping on this.

**Comment by UnixJunkie** [comment]
I m not the maintainer of this software

**Comment by ilovezfs** [comment]
@andyli I think you may need to contact

Jean-Christophe DOT Filliatre AT lri.fr

for this to have a chance of getting merged.

See https://opam.ocaml.org/packages/ptmap/ and https://www.lri.fr/~filliatr/software.en.html

**Comment by UnixJunkie** [comment]
@backtracking on github is Jean-Christophe

**Comment by ilovezfs** [comment]
@backtracking any thoughts on this PR?

**Comment by backtracking** [comment]
Sorry for having been so late with this PR. I've been disconnected for a while and too busy the rest of the time.

**Comment by andyli** [comment]
Thank you, @backtracking. It would be even nicer if you can tag a new release :)

**Comment by backtracking** [comment]
I just made a new release v2.0.2

Jean-Christophe

**Pull request merged**
